In [149]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder, StandardScaler, MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, precision_score, recall_score

# Data Loading and Initial Exploration

In [150]:
df = pd.read_csv("titanic_data_updated.csv")
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
406,407,no,third,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
285,286,no,third,"Stankovic, Mr. Ivan",male,33.0,0,0,349239,8.6625,NaN,C
837,838,no,third,"Sirota, Mr. Maurice",male,NaN,0,0,392092,8.0500,NaN,S
704,705,no,third,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,NaN,S
286,287,yes,third,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NaN,S

In [151]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

# Feature Engineering

In [152]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Cabin'] = df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
464,465,no,third,"Maisner, Mr. Simon",male,NaN,0,0,A/S 2816,8.0500,Missing,S,1,M
486,487,yes,first,"Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)",female,35.0,1,0,19943,90.0000,C93,S,2,C
181,182,no,second,"Pernot, Mr. Rene",male,NaN,0,0,SC/PARIS 2131,15.0500,Missing,C,1,M
73,74,no,third,"Chronopoulos, Mr. Apostolos",male,26.0,1,0,2680,14.4542,Missing,C,2,M
582,583,no,second,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,Missing,S,1,M

In [153]:
df['Deck'].value_counts()

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [154]:
X = df.drop('Survived', axis=1)
y = df['Survived']

# Randrom state , Stratify and Train Test Split

In [155]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Implementation of Preprocessor Pipeline

In [156]:
# Pipeline
# Numerical Values
p1 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler())
    ]
)

p2 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', MinMaxScaler())
    ]
)

In [157]:
categories = [['third', 'second', 'first']]

In [158]:
# Pipeline
# Categorical Column
p3 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'))
    ]
)

p4 = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OrdinalEncoder(categories=categories)),
        ('scaler', MinMaxScaler())
    ]
)

In [159]:
preprocessor = ColumnTransformer(
    transformers=[
        ('pipe_1', p1, ['Age']),
        ('pipe_2', p2, ['Fare', 'Family_Size']),
        ('pipe_3', p3, ['Embarked', 'Sex', 'Deck']),
        ('pipe_4', p4, ['Pclass']),
    ],
    remainder='drop'
)
preprocessor

ColumnTransformer(transformers=[('pipe_1',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['Age']),
                                ('pipe_2',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Fare', 'Family_Size']),
                                ('pipe_3',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Embarked', 'Sex', 'Deck']),
                                ('pipe_4',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(categories=[['third',
                                                                              'second',
                                                                              'first']])),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Pclass'])])

# Label Encoding

In [160]:
le = LabelEncoder()

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

# Training the Model

In [161]:
lr_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', LogisticRegression(class_weight='balanced', max_iter=1000))
    ]
)
lr_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipe_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipe_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipe_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_freq...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Deck']),
                                                 ('pipe_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [162]:
lr_model.fit(X_train, y_train)

lr_model['model'].classes_
lr_model['model'].coef_
lr_model['model'].intercept_

array([1.86583369])

In [163]:
y_pred = lr_model.predict(X_test)

lr_model.predict_proba(X_test)

array([[0.86250724, 0.13749276],
       [0.92185031, 0.07814969],
       [0.74629618, 0.25370382],
       [0.92223345, 0.07776655],
       [0.23460179, 0.76539821],
       [0.41618011, 0.58381989],
       [0.23706975, 0.76293025],
       [0.58977302, 0.41022698],
       [0.52751483, 0.47248517],
       [0.79720633, 0.20279367],
       [0.77216932, 0.22783068],
       [0.82447686, 0.17552314],
       [0.31526778, 0.68473222],
       [0.70897134, 0.29102866],
       [0.41869444, 0.58130556],
       [0.73947197, 0.26052803],
       [0.44218511, 0.55781489],
       [0.8626754 , 0.1373246 ],
       [0.79673722, 0.20326278],
       [0.22398311, 0.77601689],
       [0.8626754 , 0.1373246 ],
       [0.2038076 , 0.7961924 ],
       [0.86351383, 0.13648617],
       [0.43438672, 0.56561328],
       [0.859127  , 0.140873  ],
       [0.03125334, 0.96874666],
       [0.48026201, 0.51973799],
       [0.61935982, 0.38064018],
       [0.79192773, 0.20807227],
       [0.79577908, 0.20422092],
       [0.87999359, 0.12000641],
       [0.05148748, 0.94851252],
       [0.83027804, 0.16972196],
       [0.58930565, 0.41069435],
       [0.78426786, 0.21573214],
       [0.75227552, 0.24772448],
       [0.78351981, 0.21648019],
       [0.39655039, 0.60344961],
       [0.77216932, 0.22783068],
       [0.16732524, 0.83267476],
       [0.81324168, 0.18675832],
       [0.02693536, 0.97306464],
       [0.85616062, 0.14383938],
       [0.13383773, 0.86616227],
       [0.22910955, 0.77089045],
       [0.81948236, 0.18051764],
       [0.86251132, 0.13748868],
       [0.45429667, 0.54570333],
       [0.13192497, 0.86807503],
       [0.11847594, 0.88152406],
       [0.06618753, 0.93381247],
       [0.33801936, 0.66198064],
       [0.21600387, 0.78399613],
       [0.75260273, 0.24739727],
       [0.31213128, 0.68786872],
       [0.84516917, 0.15483083],
       [0.87480419, 0.12519581],
       [0.26766768, 0.73233232],
       [0.26958734, 0.73041266],
       [0.6303831 , 0.3696169 ],
       [0.26200197, 0.73799803],
       [0.2786366 , 0.7213634 ],
       [0.79059389, 0.20940611],
       [0.84521545, 0.15478455],
       [0.48288927, 0.51711073],
       [0.29130497, 0.70869503],
       [0.07302776, 0.92697224],
       [0.87589186, 0.12410814],
       [0.52983669, 0.47016331],
       [0.71059247, 0.28940753],
       [0.09569497, 0.90430503],
       [0.79689912, 0.20310088],
       [0.25712004, 0.74287996],
       [0.03647361, 0.96352639],
       [0.77399653, 0.22600347],
       [0.9208728 , 0.0791272 ],
       [0.88383566, 0.11616434],
       [0.85503949, 0.14496051],
       [0.60116159, 0.39883841],
       [0.29147714, 0.70852286],
       [0.82295956, 0.17704044],
       [0.79804512, 0.20195488],
       [0.77981565, 0.22018435],
       [0.84520352, 0.15479648],
       [0.16600782, 0.83399218],
       [0.37289233, 0.62710767],
       [0.87339807, 0.12660193],
       [0.3622289 , 0.6377711 ],
       [0.32306809, 0.67693191],
       [0.0190158 , 0.9809842 ],
       [0.42977994, 0.57022006],
       [0.42989693, 0.57010307],
       [0.9090994 , 0.0909006 ],
       [0.86269284, 0.13730716],
       [0.58566998, 0.41433002],
       [0.19523014, 0.80476986],
       [0.34301543, 0.65698457],
       [0.77216932, 0.22783068],
       [0.88383566, 0.11616434],
       [0.84130815, 0.15869185],
       [0.71372705, 0.28627295],
       [0.0657748 , 0.9342252 ],
       [0.21597828, 0.78402172],
       [0.08673613, 0.91326387],
       [0.84518947, 0.15481053],
       [0.39508387, 0.60491613],
       [0.64691003, 0.35308997],
       [0.86269284, 0.13730716],
       [0.80831227, 0.19168773],
       [0.45009362, 0.54990638],
       [0.77216932, 0.22783068],
       [0.94883269, 0.05116731],
       [0.84996698, 0.15003302],
       [0.42269691, 0.57730309],
       [0.15136942, 0.84863058],
       [0.77216932, 0.22783068],
       [0.67804184, 0.32195816],
       [0.79036592, 0.20963408],
       [0.84939224, 0.15060776],
       [0.82734709, 0.17265291],
       [0.85459968, 0.14540032],
       [0.25817472, 0.74182528],
       [0.91383034, 0.08616966],
       [0.31489622, 0.68510378],
       [0.80255246, 0.19744754],
       [0.79446933, 0.20553067],
       [0.44321444, 0.55678556],
       [0.38884315, 0.61115685],
       [0.83778788, 0.16221212],
       [0.56753947, 0.43246053],
       [0.85710336, 0.14289664],
       [0.85461154, 0.14538846],
       [0.23460179, 0.76539821],
       [0.77231906, 0.22768094],
       [0.62562372, 0.37437628],
       [0.81373205, 0.18626795],
       [0.04576286, 0.95423714],
       [0.77216932, 0.22783068],
       [0.21598434, 0.78401566],
       [0.86266833, 0.13733167],
       [0.48408142, 0.51591858],
       [0.75663058, 0.24336942],
       [0.34563039, 0.65436961],
       [0.51997153, 0.48002847],
       [0.75448994, 0.24551006],
       [0.65089446, 0.34910554],
       [0.86269284, 0.13730716],
       [0.73824426, 0.26175574],
       [0.0878375 , 0.9121625 ],
       [0.14082539, 0.85917461],
       [0.85006689, 0.14993311],
       [0.65972357, 0.34027643],
       [0.06354362, 0.93645638],
       [0.16579126, 0.83420874],
       [0.65735144, 0.34264856],
       [0.09592645, 0.90407355],
       [0.7328147 , 0.2671853 ],
       [0.85384911, 0.14615089],
       [0.68541427, 0.31458573],
       [0.14882429, 0.85117571],
       [0.31134584, 0.68865416],
       [0.05595871, 0.94404129],
       [0.21598434, 0.78401566],
       [0.09717383, 0.90282617],
       [0.09908372, 0.90091628],
       [0.29169299, 0.70830701],
       [0.8656735 , 0.1343265 ],
       [0.40163083, 0.59836917],
       [0.16637201, 0.83362799],
       [0.31437522, 0.68562478],
       [0.90779051, 0.09220949],
       [0.79689912, 0.20310088],
       [0.47666969, 0.52333031],
       [0.69483004, 0.30516996],
       [0.18649294, 0.81350706],
       [0.8139701 , 0.1860299 ],
       [0.74043546, 0.25956454],
       [0.02858941, 0.97141059],
       [0.79772156, 0.20227844]])

# Evaluation

In [164]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)
precision = precision_score(y_test, y_pred)
print(precision)
recall = recall_score(y_test, y_pred)
print(recall)

0.7597765363128491
0.6666666666666666
0.7536231884057971